---
site_name: Sobakode
site_description: No more spaghetti code
site_url: https://mrtolkien.github.io/sobakode

repo_name: mrtolkien/sobakode
repo_url: https://github.com/mrtolkien/sobakode

theme:
  name: material
  logo: assets/sobakode.png
  favicon: assets/sobakode.png
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

    # Insiders only but would like to use it
    - toc.follow

    - search.highlight
    - search.share
    - search.suggest

  palette:
    - scheme: slate
      primary: brown
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: brown
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mrtolkien/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TolkiCasts

nav:
  - Introduction: index.md
  - Git:
      # - git/index.md
      - Branches: 1-git/1-branches.md
      - Pull Requests: 1-git/2-PRs.md
      - Releases: 1-git/3-releases.md

  - Tests:
      - Why: 2-tests/1-why.md
      - How: 2-tests/1-how.md

  - Python:
      # - python/index.md
      - Environment: python/environment.md
      - Packaging: python/packaging.md
