---
site_name: Sobakode
site_description: No more code spaghetti
site_url: https://mrtolkien.github.io/sobakode

repo_name: mrtolkien/sobakode
repo_url: https://github.com/mrtolkien/sobakode

theme:
  name: material
  # logo: https://raw.githubusercontent.com/k8s-at-home/organization/main/logo/k8s-at-home-32.png
  # favicon: https://raw.githubusercontent.com/k8s-at-home/organization/main/logo/k8s-at-home-32.png
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: slate
      primary: deep purple
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mrtolkien/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TolkiCasts

nav:
  - Introduction: index.md
  # - Git:
  #     - Prerequisite: 1-workstation/0-prerequisite.md
  #     - Tools: 1-workstation/1-tools.md
  #     - Git: 1-workstation/2-git-repo.md
  #     - Age + SOPS: 1-workstation/3-age-sops.md
